### ISSUE TITLE
Range Error

### ISSUE THREAD

**Issue by frankdai** [43081j/id3#25]
```shell
d:\Code\mp3\node_modules\id3js\dist\id3.js:928
                                                        frameBit = dv.getUint8(p
osition + i);
                                                                      ^
RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (native)
    at d:\Code\mp3\node_modules\id3js\dist\id3.js:928:22
    at d:\Code\mp3\node_modules\id3js\dist\id3.js:118:4
    at FSReqWrap.wrapper [as oncomplete] (fs.js:529:17)
```

**Comment by gedaiu** [comment]
I get the same error... there is a workaround for this?

**Comment by jmcgavin** [comment]
Also experience this issue
